# Attention, all ports are exposed to localhost. Use for debug only

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    env_file:
      - ../configs/.env.template
    networks:
      - service-network

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    env_file:
      - ../configs/.env.template
    networks:
      - service-network

  postgres:
    image: postgres:15
    container_name: postgres_container
    env_file:
      - ../configs/.env.template
    networks:
      - service-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 10s
      retries: 10
    env_file:
      - ../configs/.env.template
    networks:
      - service-network

networks:
  service-network:
    driver: bridge