services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    env_file:
      - ../configs/Docker.env.template
    networks:
      - service-network

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    env_file:
      - ../configs/Docker.env.template
    networks:
      - service-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../configs/:/etc/nginx/
    depends_on:
      - backend
    networks:
      - service-network

  postgres:
    image: postgres:15
    container_name: postgres_container
    env_file:
      - ../configs/Docker.env.template
    networks:
      - service-network
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_container
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 10s
      retries: 10
    env_file:
      - ../configs/Docker.env.template
    networks:
      - service-network

  backend:
    build:
      context: ..
      dockerfile: build/main_server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - service-network

networks:
  service-network:
    driver: bridge