stages:
  - linting
  - test
  - build
  - integration tests
  - deploy

linting:
  stage: linting
  image: golang:1.22-alpine
  script:
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.62.2
    - ./bin/golangci-lint --version
    - ./bin/golangci-lint run

static test:
  stage: test
  needs: []
  image: golang:1.22-alpine
  script:
    - go mod download
    - go test -count=1 -cover -v ./...

build compose file:
  stage: build
  needs: ["static test"]
  script:
    - docker compose -f .\deployments\docker-compose.yml down
    - docker compose -f .\deployments\docker-compose.yml build

build integration tests:
  stage: build
  needs: ["static test"]
  script:
    - docker stop tests:latest
    - docker build -t tests:latest -f .\build\integrationTests\Dockerfile ./

integration tests:
  stage: integration tests
  needs: ["build compose file", "build integration tests"]
  script:
    - docker compose -f .\deployments\docker-compose.yml up -d
    - docker run --network=deployments_service-network --name test-container -it tests:latest

deploy job:
  stage: deploy
  needs: ["integration tests"]
  script:
    - docker compose -f ./deployments/docker-compose.yml down -v
    - docker compose -f ./deployments/docker-compose.yml up -d
