stages:
  - linting
  - test
  - build
  - integration tests
  - deploy

linting:
  stage: linting
  image: alpine:latest
  script:
    - echo "Linting ..."
    - sleep 5

static test:
  stage: test
  script:
    - echo "Testing static tests ..."
    - sleep 5

build compose file:
  stage: build
  needs: ["linting", "static test"]
  script:
    - echo "Building ..."
    - sleep 5

build integration tests:
  stage: build
  needs: ["linting", "static test"]
  script:
    - echo "Building tests ..."
    - sleep 5

integration tests:
  stage: integration tests
  needs: ["build compose file", "build integration tests"]
  script:
    - echo "Running integration tests ..."
    - sleep 5

deploy job:
  stage: deploy
  needs: ["integration tests"]
  script:
    - echo "Deploying ..."
    - sleep 5
